# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneModel', models.CharField(max_length=20)),
                ('dataPlan', models.CharField(choices=[('con data', 'Si'), ('sin data', 'No')], max_length=8)),
            ],
        ),
    ]
