# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='phoneNumber',
            field=models.CharField(default='no', max_length=20),
            preserve_default=False,
        ),
    ]
