# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_fleet_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='fleet',
            name='dataPlan',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2),
        ),
    ]
