# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20171012_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='dataPlan',
            field=models.CharField(choices=[('Con data', 'Si'), ('Sin data', 'No')], max_length=2),
        ),
    ]
