# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_auto_20171012_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='dataPlan',
            field=models.CharField(choices=[('con data', 'Si'), ('sin data', 'No')], max_length=8),
        ),
    ]
