# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_auto_20171012_1938'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bloodType',
        ),
        migrations.DeleteModel(
            name='maritalStatus',
        ),
    ]
