# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20171012_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='chiefDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiefName', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='settings.chiefDepartment'),
            preserve_default=False,
        ),
    ]
