# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computersName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='computerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computersType', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='computers',
            name='typeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.computerType'),
        ),
    ]
