# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20171012_2228'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='typeName',
        ),
        migrations.DeleteModel(
            name='Computers',
        ),
    ]
