# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0001_initial'),
        ('settings', '0001_initial'),
        ('equipments', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.CharField(max_length=40, unique=True)),
                ('photo', models.ImageField(upload_to='STATIC_URL/photos/')),
                ('firstNames', models.CharField(max_length=80)),
                ('lastNames', models.CharField(max_length=80)),
                ('homePhone', models.CharField(max_length=20)),
                ('celPhone', models.CharField(max_length=20)),
                ('birthPlace', models.CharField(max_length=60)),
                ('computerAssigned', models.ManyToManyField(blank=True, to='equipments.computerType')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Department')),
                ('fleetAssigned', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.Fleet')),
                ('systemsAssigned', models.ManyToManyField(blank=True, to='systems.Systems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
