# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.CharField(max_length=40, unique=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('firstNames', models.CharField(max_length=80)),
                ('lastNames', models.CharField(max_length=80)),
                ('homePhone', models.CharField(max_length=20)),
                ('celPhone', models.CharField(max_length=20)),
                ('sonsQty', models.PositiveIntegerField()),
                ('birthDate', models.DateField()),
                ('birtPlace', models.CharField(max_length=60)),
                ('bloodType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.bloodType')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.Department')),
                ('maritalStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.maritalStatus')),
            ],
        ),
    ]
