# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='birtPlace',
            new_name='birthPlace',
        ),
    ]
