# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20171012_1516'),
        ('workers', '0002_auto_20171012_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fleetAssigned',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.Fleet'),
            preserve_default=False,
        ),
    ]
