# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='fleetAssigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.Fleet'),
        ),
    ]
