# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171026_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
