# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20171012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='computerAssigned',
            field=models.ManyToManyField(blank=True, to='equipments.Computers'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fleetAssigned',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.Fleet'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='systemsAssigned',
            field=models.ManyToManyField(blank=True, to='systems.Systems'),
        ),
    ]
