# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_auto_20171012_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='bloodType',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='sonsQty',
        ),
    ]
