# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20171012_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(upload_to='workers/photos/'),
        ),
    ]
