# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_auto_20171016_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(upload_to='STATIC_URL/photos/'),
        ),
    ]
