# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionName', models.CharField(choices=[('Lectura', 'Lectura'), ('Escritura', 'Escritura'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='modules',
            name='permission',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='systems.Permissions'),
            preserve_default=False,
        ),
    ]
