# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20171012_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permissionName',
            field=models.CharField(max_length=20),
        ),
    ]
